/**VEHICLE AD CONSTANTS */
export const ADD_VEHICLE_AD = "ADD_VEHICLE_AD";
export const UPDATE_VEHICLE_AD = "UPDATE_VEHICLE_AD";
export const DELETE_VEHICLE_AD = "DELETE_VEHICLE_AD";
export const GET_VEHICLE_AD_BY_ID = "GET_VEHICLE_AD_BY_ID";
export const GET_ALL_VEHICLE_ADS = "GET_ALL_VEHICLE_ADS";