/**VEHICLE AD CONSTANTS */
export const ADD_VEHICLE_AD = "ADD_VEHICLE_AD";
export const UPDATE_VEHICLE_AD = "UPDATE_VEHICLE_AD";
export const DELETE_VEHICLE_AD = "DELETE_VEHICLE_AD";
export const GET_VEHICLE_AD_BY_ID = "GET_VEHICLE_AD_BY_ID";
export const GET_ALL_VEHICLE_ADS = "GET_ALL_VEHICLE_ADS";
export const GET_PUBLISHED_VEHICLE_ADS = "GET_PUBLISHED_VEHICLE_ADS";
export const UPDATE_PENDING_VEHICLE_ADS = "UPDATE_PENDING_VEHICLE_ADS";

/**SPARE PARTS AD CONSTANTS */
export const ADD_SPAREPARTS_AD = "ADD_SPAREPARTS_AD";
export const UPDATE_SPAREPARTS_AD = "UPDATE_SPAREPARTS_AD";
export const DELETE_SPAREPARTS_AD = "DELETE_SPAREPARTS_AD";
export const GET_SPAREPARTS_AD_BY_ID = "GET_SPAREPARTS_AD_BY_ID";
export const GET_ALL_SPAREPARTS_ADS = "GET_ALL_SPAREPARTS_ADS";
export const GET_PUBLISHED_SPAREPARTS_ADS = "GET_PUBLISHED_SPAREPARTS_ADS";
export const UPDATE_PENDING_SPAREPARTS_ADS = "UPDATE_PENDING_SPAREPARTS_ADS";

// CATEGORY CONSTANTS

export const GET_ALL_CATEGORIES = "GET_ALL_CATEGORIES";
export const DELETE_CATEGORIES = "DELETE_CATEGORIES";

/**user  CONSTANTS */
export const ADD_USER = "ADD_USER";
export const UPDATE_USER = "UPDATE_USER";
